export enum ThirdPartyType {
  CLIENT = "CLIENT", // CLIENTE
  SUPPLIER = "SUPPLIER", // PROVEEDOR
  CONTRACTOR = "CONTRACTOR", // CONTRATISTA
  EMPLOYEE = "EMPLOYEE", // EMPLEADO
  BOTH = "BOTH", // AMBOS
}