export enum SurveyType {
  SATISFACTION = "SATISFACTION",
  EVALUATION = "EVALUATION",
  CHECKLIST = "CHECKLIST",
  PROGRESS = "PROGRESS",
  OTHER = "OTHER",
}

export enum SurveyStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  CLOSED = "CLOSED",
}

export enum QuestionType {
  TEXT = "TEXT",
  TEXTAREA = "TEXTAREA",
  SINGLE_CHOICE = "SINGLE_CHOICE",
  MULTI_CHOICE = "MULTI_CHOICE",
  RATING = "RATING",
  YES_NO = "YES_NO",
  NUMBER = "NUMBER",
  DATE = "DATE",
}